---
- name: Hello Controller
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "Run job template"
      condition: event.i == 5
      action:
        run_job_template:
          name: hello
          organization: Default
          job_args:
            extra_vars:
              hello: Joon
          retries: 1
          delay: 10
...
